name = "shopify-backend"
main = "cloudflare-worker-pdf-template.js"
compatibility_date = "2024-01-01"
node_compat = true

# Environment variables (aggiungi le chiavi su Cloudflare Dashboard)
[vars]
SHOPIFY_API_VERSION = "2024-10"
ALLOWED_ORIGIN = "*"

# KV Namespace Bindings
[[kv_namespaces]]
binding = "PFLEGEBOX_SUBMISSIONS"
id = "ffdde73335f943f09e9fc9ecb46d9c0d"

# R2 Bucket Bindings
[[r2_buckets]]
binding = "PDF_TEMPLATE"
bucket_name = "pflegebox-templates"

# D1 Database Bindings
[[d1_databases]]
binding = "CUSTOMERS_DB"
database_name = "pflegeteufel-customers"
database_id = "baaad9c0-081f-4377-a313-0ce75d5e5bc1"

# Secrets (da configurare con: wrangler secret put NOME_VARIABILE)
# - SHOPIFY_ADMIN_TOKEN
# - SHOPIFY_SHOP
# - WORKER_SHARED_KEY
# - RESEND_API_KEY
# - SENDGRID_API_KEY (opzionale)
