name: Deploy to Shopify

on:
  push:
    branches:
      - main
    paths:
      - 'templates/**'
      - 'sections/**'
      - 'snippets/**'
      - 'assets/**'
      - 'layout/**'
      - 'config/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli @shopify/theme

      - name: Deploy to Shopify
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: |
          shopify theme push --theme=${{ secrets.SHOPIFY_THEME_ID }} --allow-live --only=templates/ --only=sections/ --only=snippets/
